name = "MLJEnsembles"
uuid = "50ed68f4-41fd-4504-931a-ed422449fee0"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.2"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ComputationalResources = "ed09eef8-17a6-5b46-8889-db040fac31e3"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CategoricalArrays = "0.8, 0.9, 0.10"
ComputationalResources = "0.3"
Distributions = "0.21, 0.22, 0.23, 0.24, 0.25"
MLJBase = "0.18"
MLJModelInterface = "0.4.1, 1.1"
ProgressMeter = "1.1"
ScientificTypes = "2"
StatsBase = "0.32, 0.33"
julia = "1.1"

[extras]
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MLJModels", "NearestNeighborModels", "StableRNGs", "Test"]
