name = "MLJEnsembles"
uuid = "50ed68f4-41fd-4504-931a-ed422449fee0"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.4.4"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CategoricalDistributions = "af321ab8-2d2e-40a6-b165-3d674595d28e"
ComputationalResources = "ed09eef8-17a6-5b46-8889-db040fac31e3"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScientificTypesBase = "30f210dd-8aff-4c5f-94ba-8e64358c1161"
StatisticalMeasuresBase = "c062fc1d-0d66-479b-b6ac-8b44719de4cc"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CategoricalArrays = "1"
CategoricalDistributions = "0.2"
ComputationalResources = "0.3"
Distributions = "0.21, 0.22, 0.23, 0.24, 0.25"
MLJModelInterface = "1.10"
ProgressMeter = "1.1"
ScientificTypesBase = "2,3"
StatisticalMeasuresBase = "0.1"
StatsBase = "0.32, 0.33, 0.34"
julia = "1.6"

[extras]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatisticalMeasures = "a19d573c-0a75-4610-95b3-7071388c7541"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distances", "MLJBase", "NearestNeighbors", "Serialization", "StableRNGs", "StatisticalMeasures", "Test"]